### ISSUE TITLE
Gtags support (maybe?)

### ISSUE THREAD

**Issue by amgdev9** [netmute/ctags-lsp#1]
Gtags (https://www.gnu.org/software/global/) are a enhanced version of ctags that provides search references and incremental ctags db updates. It can use universal ctags as a backend, so all languages supported by universal ctags are supported.

Also, with search references support, features like rename symbol should be easy to implement

**Comment by pidgeon777** [comment]
Seems like a good suggestion. Does `gtags` for Windows exist?

**Comment by amgdev9** [comment]
> Seems like a good suggestion. Does `gtags` for Windows exist?

There is not an official package for windows but its posix compliant, so it is possible to compile from source using mingw/cygwin for example

**Comment by netmute** [comment]
I don't see the benefits supporting gtags would bring. The only feature of universal-ctags that's being used is parsing the project and passing the resulting JSON on to the language server. Everything else is done by the server itself.

gtags offers no improvement to this workflow, and I don't think it supports JSON output at all.
